### ISSUE TITLE
Doc Request: Add FAQ and/or Roadmap

### ISSUE THREAD

**Issue by tbirdso** [KitwareMedical/SlicerMixedReality#3]
As someone who is interested in Slicer's extended support for XR, it would be helpful to have a high-level "FAQ" section or roadmap of features intended for this module.

## Questions to Answer
- [ ] Is `SlicerMixedReality` intended as the OpenXR equivalent of https://github.com/KitwareMedical/SlicerVirtualReality, which is for OpenVR? Is it anticipated that `SlicerMixedReality` will eventually reach feature parity and replace `SlicerVirtualReality` as the industry moves towards OpenXR?
- [ ] What devices are planned for support by `SlicerMixedReality`? Is it planned for all devices covered by the [`VTK::RenderingOpenXR`](https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXR#supported-devices) module to eventually be available through SlicerMixedReality, or is only HoloLens remoting support through `VTK::RenderingOpenXRRemoting` planned?
- [ ] To what degree will OpenXR features be leveraged? Will both VR and passthrough AR be available on capable devices such as the Meta Quest headsets? Will AR remoting be available for devices in addition to the Microsoft HoloLens? What input schemes will be supported?
- [ ] Are there other planned features that would fit into the scope of this module, such as collaborative XR viewing?

To be clear, I am not necessarily asking for concrete answers or technical details. Any discussion that module developers could contribute to clarify the planned scope of this module and where development *may* go would be appreciated.

## References

To aid in discussion, we have recently expanded documentation for VTK supported XR devices and input mechanisms here:
https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXR#vtkrenderingopenxr
https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXRRemoting#vtkrenderingopenxrremoting
https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenVR#vtkrenderingopenvr

**Comment by LucasGandel** [comment]
@jcfr is probably the right person to confirm the roadmap, but here is my understanding FWIW

1. As the industry moves towards OpenXR, SlicerMixedReality aims to be the OpenXR equivalent of SlicerVirtualReality for VR headsets. But it also allows for leveraging AR, which is a huge potential improvement.
2. So far Hololens2 (hence OpenXRRemoting) is the primary target ([see WIP](https://github.com/KitwareMedical/SlicerMixedReality/pull/2)), but adding "plain" OpenXR support is required to fulfil requirement 1. (I am not sure something is planned in this direction, but I think this must definitely be considered)
3. Supporting all devices and feature provided by [VTK::RenderingOpenXR](https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXR#supported-devices) would be a good start.
4. Not that I am aware of for now, but the long term would be to have SlicerMixedReality being the standard for medical image processing/visualization in XR, IGT...

Thank you again for the great work around the VTK OpenXR modules documentation! 🥇 🎉 🚀

**Comment by jcfr** [comment]
> Is `SlicerMixedReality` intended as the OpenXR equivalent of https://github.com/KitwareMedical/SlicerVirtualReality, which is for OpenVR? Is it anticipated that `SlicerMixedReality` will eventually reach feature parity and replace `SlicerVirtualReality` as the industry moves towards OpenXR?

Current plan is to refactor `SlicerVitualReality` to support both `OpenVR` and `OpenXR` and provide components re-usable in the `SlicerMixedReality` extension.

This means that the `SlicerMixedReality` will depend on `SlicerVitualReality`:

* https://github.com/KitwareMedical/SlicerVirtualReality/issues/121


--------

> What devices are planned for support by `SlicerMixedReality`? Is it planned for all devices covered by the [`VTK::RenderingOpenXR`](https://gitlab.kitware.com/vtk/vtk/-/tree/master/Rendering/OpenXR#supported-devices) module to eventually be available through SlicerMixedReality, or is only HoloLens remoting support through `VTK::RenderingOpenXRRemoting` planned?

The virtual reality devices integrating with `OpenXR` will be supported through the `SlicerVirtualReality` extension, the `SlicerMixedReality` will support devices based on the VTK support.

--------

> To what degree will OpenXR features be leveraged? Will both VR and passthrough AR be available on capable devices such as the Meta Quest headsets? Will AR remoting be available for devices in addition to the Microsoft HoloLens? What input schemes will be supported?

See @LucasGandel comment in https://github.com/KitwareMedical/SlicerMixedReality/issues/3#issuecomment-1662401904

--------

> Are there other planned features that would fit into the scope of this module, such as collaborative XR viewing?

Similarly to collaborative VR [^1], adding support for collaborative XR is indeed a sensible path forward. 

[^1]: https://www.youtube.com/watch?v=rG9ST6xv6vg

**Comment by tbirdso** [comment]
> The virtual reality devices integrating with OpenXR will be supported through the SlicerVirtualReality extension, the SlicerMixedReality will support devices based on the VTK support.

@jcfr Would you please clarify this point? As it is written this seems to imply that SlicerVirtualReality will not depend on VTK, is that correct?

Maybe it is too early now, but eventually it would be extremely helpful to have a README section explicitly stating what features are supported in SlicerMixedReality that are not supported or planned for support in SlicerVirtualReality.

**Comment by tbirdso** [comment]
> Current plan is to refactor SlicerVirtualReality to support both OpenVR and OpenXR and provide components re-usable in the SlicerMixedReality extension.

IMO under the current naming scheme it will be unclear to developers which module to start from or install, especially for developers who are familiar with "OpenXR" or "mixed reality" as the newer standard. It is understandable that the scope of this module may have changed since its inception. I suggest considering other names for this module to clarify that it will contain extended feature support for the "SlicerVirtualReality" module. "SlicerAdvancedVirtualReality" may be sufficient.

**Comment by jcfr** [comment]
> > The virtual reality devices integrating with OpenXR will be supported through the SlicerVirtualReality extension, the SlicerMixedReality will support devices based on the VTK support.

> Would you please clarify this point? As it is written this seems to imply that SlicerVirtualReality will not depend on VTK, is that correct?

The comment https://github.com/KitwareMedical/SlicerMixedReality/issues/3#issuecomment-1715691093 has been updated to explicitly mention `vtkRenderingOpenXR` and `vtkRenderingOpenXRRemoting`

-------------------

> IMO under the current naming scheme it will be unclear to developers which module to start from or install

Users usually discover extensions (and associated modules) though the extension manager and  descriptions reported there should help clarify.

> `SlicerVirtualReality`, `SlicerAdvancedVirtualReality` and `SlicerMixedReality` 

Once we have functional integration, we could revisit the split to reduce confusion. In the meantime, I suggest we discuss proposal described in:
 
* https://github.com/KitwareMedical/SlicerVirtualReality/issues/121

> Maybe it is too early now, but eventually it would be extremely helpful to have a README section explicitly stating what features are supported in SlicerMixedReality that are not supported or planned for support in SlicerVirtualReality.

Ditto. A README similar to the one added the the SlicerVirtualReality extension[^1] will be added.

In the meantime, I envision that the SlicerMixedReality extension will provide a module allowing to integrate with the mixed reality headset currently supported by VTK through `vtkRenderingOpenXRRemoting`.

[^1]: https://github.com/KitwareMedical/SlicerVirtualReality#slicervirtualreality

**Comment by tbirdso** [comment]
Thanks @jcfr . Responding to the edits in https://github.com/KitwareMedical/SlicerMixedReality/issues/3#issuecomment-1715691093:

> The virtual reality devices integrating with OpenXR will be supported through the SlicerVirtualReality extension (itself depending on vtkRenderingOpenXR), the SlicerMixedReality will support devices based on the VTK support (currently provided through vtkRenderingOpenXRRemoting).

> In the meantime, I envision that the SlicerMixedReality extension will provide a module allowing to integrate with the mixed reality headset currently supported by VTK through vtkRenderingOpenXRRemoting.

I suggest renaming this module to `SlicerVirtualRealityRemoting` if that is the differentiating functionality.
